version: '3.8'

services:
  privilege-escalation:
    build: 
      context: .
    container_name: privilege-escalation
    ports:
      - "1337:1337"
      - "2222:22"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true
    environment:
      - FLAG=${FLAG}
