version: '3.8'
services:
  resiliencia-malware:
    build:
      context: .
    container_name: resiliencia-malware
    ports:
      - "80:80" 
      - "2222:22"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true
    environment:
      - FLAG=${FLAG}
